### ISSUE TITLE
Geth monitoring & logging tracking issue

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#318]
Console log

 - [x] status every minute #127 

Logging to filesystem

 - [x] peer discovery log
 - [x] peer exchange log #317
 - [x] blockchain import log

**Comment by whilei** [comment]
Also referencing:

- [ ] monitor and debug metrics #268 -- implement programmatically-available timers and meters available via RPC/+JSON-CLI (PR WIP at #315)

----

_Notes:_

__Logging to filesystem:__
Currently, flag `--vmodule` allows per-module log leveling, eg. `--vmodule="eth/*=6,p2p=5"` and `--log-dir` allows writing per-session logs to a single file. Logging per module to the filesystem builds on a combination of these ideas and functionalities.

**Comment by whilei** [comment]
Closing, since mlog has been merged to master and API is awaiting review/approval via #376
