### ISSUE TITLE
Milestone: configure reproducible consensus/integration tests

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#322]
Goal: define specs and implement in code reproducible integration and consensus tests to be used as a part of "internal testing" for pre-release geth clients. This suite is intended to be run on a cloud service, using a private cluster of nodes to simulate normal and edge-case uses and scenarios.

There are a few existing testing tools which may be relevant:

[list TBD]

And a tentative list of test cases to be addressed:
 - [ ] fork-defined configuration changes (eg. ECIP 1017)
 - [ ] sending transactions
 - [ ] mining rewards
 - [ ] misbehaving peers/known attack scenarios
- [ ] Parity + ETHF friendliness
[...]

**Comment by whilei** [comment]
Closing via https://github.com/ethereumproject/ecip1017test
