### ISSUE TITLE
Release 4.1.1 - Stability, db robustness, and some other random things

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#371]
__Goal of the milestone__: stabilize client behavior for edge cases, improve database robustness
__Release deadline__: Nov 1

Central:
- [ ] Issue #274 - further investigate database corruption/restart; reproducible? Lead: @tzdybal 
- [ ] PR #277 - finish and merge PR resolving above
- [ ] Issue #346 - resolve; reproduce or invalid?
- [ ] Issue #339 - resolve; reproduce or invalid?

Miscellaneous:
- [ ] Issue #361 - setup homebrew installation
- [ ] Issue #364 - resolve; remove unimplemented methods from `ethereum_js`
- [ ] PR #365 - review and merge; implement logging-related methods for debugApi
- [ ] Issue #352 - resolve _rounding_ ambiguity related to Parity/Geth implementation difference. See related links from issue page, especially https://github.com/ethereumproject/ECIPs/issues/15. This is more an ECIP human-consensus issue than a code issue. Lead: @whilei

**Comment by whilei** [comment]
Closing in favor of using milestone system, moved to https://github.com/ethereumproject/go-ethereum/milestone/9.
