### ISSUE TITLE
[trackingissue] Milestone 4.3 - EVM+SputnikVM

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#372]
This issue tracks undocumented and/or external requirements for  https://github.com/ethereumproject/go-ethereum/milestone/10

@sudachen This milestone could use more specifics -- would you please...
- [ ] _create issues_ for relevant steps required to accomplish integration with sputnikvm, eg. setup RPC/IPC tests, run benchmarks, debug/review/integrate with @sorpaas
- [ ] add them here to this milestone
- [x] push your branch `sudachen:multivm-1` to upstream at `ethereumproject:multivm-1` so changes to and reviews of the feature are readily and centrally available for other contributors

Misc:
- [ ] Disable difficulty bomb - ECIP #humanconsensus (?)

Issues:
- [ ] #416 Update build system to build sputnik vm as static library accessible by Go compiler.
- [ ] #432 sputnikvm panicked at 'arithmetic operation overflow'
- [ ]  #429 Create build script for building with SputnikVM (rel #416)

**Comment by sudachen** [comment]
#416

**Comment by sudachen** [comment]
Issue #416  Update building system to build sputnik vm as static library accessible by Go compiler.

**Comment by sudachen** [comment]
I have added [ethereumproject/sputnikvm-libffi](https://github.com/ethereumproject/sputnikvm-libffi) repository. It contains native SVM bindings used by [machine/sputnik/machine.go](https://github.com/ethereumproject/go-ethereum/blob/multivm-1/machine/sputnik/machine.go) the implementation of Virtual Machine Abstraction.
