### ISSUE TITLE
mlog: milestone tracking issue

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#494]
### TODO: mlog
> This issue tracking development toward finalization of mlog api, implementation, and documentation

#### API
- [x] "stabilize" API points. We want to be sure that we're generating useful points, with a useful and extensible structure, and that we definitely probably don't want to get _rid_ of any of the points (breaking backwards compatibility)
  - [x] tinker around with mlog, make sure we can glean some relevant stuff, and keep an eye for data going to waste

##### Possible additions and changes
- [x] (add) Client start, fields: `clientid` (not random, not necessarily unique), `sessionid` (random, mildly unique) #499
- [x] (add) Client graceful stop, fields: `clientid` (not random, not necessarily unique), `sessionid` (random, mildly unique) #499 
- [x] (add) Synchronizing with network started, fields: `peer`, `current fast/full block`
- [x] (add) Synchronizing with network stopped, fields: `peer`, `time`, `current fast/full block`
- [x] (add) Synchronizing with network stopped, fields: `peer`, `time`, `current fast/full block`
- [x] (add) `headerchain.insert.headers`... otherwise there is little to no information about sync progress during fast sync
- [x] ~(add) Fetching headers, fields: `n` headers, `startBlock`, `peer`~ sticken because overlap with `wire` protocol. we can add later if necessary.

#### Implementation
- [x] audit test coverage and fill in gaps
- [x] do we like the way it's auto-documenting? should that be revised, extended?...

#### documentation
- [ ] publish a tutorial, piggy-backing https://github.com/ethereumproject/geth-ELK, demonstrating mlog in use via __docker containers__
  - [x] decide on what infrastructure to use... Digital ocean, kubernetes, whatever
  - [x] keep log rotation/filebeat in mind
- [x] see https://github.com/ethereumproject/go-ethereum/wiki/mlog-API. Specific line documentation here is auto-generated with `geth mdoc -md`

#### Related issues and ideas:
- possible mlog file rotation and compression - #492 
_..._

**Comment by splix** [comment]
kubernetes. we have infrastructure on Google Cloud already, with nodes and everything, just add dashboard to it

**Comment by whilei** [comment]
### PR Merge order-of-operations
- [ ] master <- #502
- [ ] #501 <- #503 
- [ ] master <- #501 
- [ ] master <- #504
